FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install deps ignoring peer dep conflicts
RUN npm ci --legacy-peer-deps

COPY . .

RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "start"]
